* Прочитать про методы оптимизации для нейронных сетей https://habr.com/post/318970/
* Реализовать самостоятельно логистическую регрессию
* Обучить ее методом градиентного спуска
* Методом nesterov momentum
* Методом rmsprop

**Дополнительное задание**

В качестве dataset’а взять Iris, оставив 2 класса:
Iris Versicolor
Iris Virginica

In [399]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [400]:
#Получаю данные
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [401]:
#Делаю удобный датасет
iris_data = pd.DataFrame(data = iris['data'], columns = iris['feature_names'])
iris_target = pd.Series(iris['target'])
iris_data['target'] = iris_target

#Убираю данные об iris setosa, меняю маркер iris virginica на 0, чтобы получить в target 0 и 1
iris_data = iris_data[iris_data.target != 0]
iris_data['target'] = iris_data.target.apply(lambda x: x if x == 1 else 0)
iris_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
50        1  
51        1  
52        1  
53        1  
54        1  
..      ...  
145       0  
146       0  
147       0  
148       0  
149       0  

[100 rows x 5 columns]

In [402]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 50 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  100 non-null    float64
 1   sepal width (cm)   100 non-null    float64
 2   petal length (cm)  100 non-null    float64
 3   petal width (cm)   100 non-null    float64
 4   target             100 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 4.7 KB


In [403]:
# Получаю целевой вектор
y = iris_data.target
y

50     1
51     1
52     1
53     1
54     1
      ..
145    0
146    0
147    0
148    0
149    0
Name: target, Length: 100, dtype: int64

In [404]:
#Получаю матрицу признаков
X = iris_data.iloc[:, :4]
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
53                 5.5               2.3                4.0               1.3
54                 6.5               2.8                4.6               1.5
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[100 rows x 4 columns]

In [405]:
#Разделяю данные на train и test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [406]:
#Обучаю модель с помощью встроенной функции
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [407]:
predict = model.predict(X_test)
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

0.9714285714285714
0.9333333333333333


In [408]:
#Функция, которая возвращает количество ошибок в предсказании в абсолютном и относительном формате.
def iris_error(models, target):
    diff = models - np.array(target)
    abs_err = sum(map(abs, diff))
    rel_err = abs_err / len(target)
    return abs_err, rel_err

In [409]:
iris_error(model.predict(X_train), y_train)

(2, 0.02857142857142857)

In [410]:
iris_error(predict, y_test)

(2, 0.06666666666666667)

In [411]:
#Сигмоид
def sygmoid(theta, x):
    L = np.matmul(x, theta.T)
    return np.array(1 / (1 + np.e ** (- (L))))

In [412]:
#Максимизация правдоподобия
def cost(theta, x, y):
    sygm = sygmoid(theta, x)
    value = (- y) * np.log(sygm) - (1 - y) * np.log(1 - sygm)
    return np.mean(value)

In [413]:
#Градиент
def gradient(theta, x, y):
    return - np.array(np.matmul((np.array(y) - sygmoid(theta, x)), x))

In [430]:
#Логистическая регрессия, обучающаяся методом градиентного спуска
def LogisticRegression_grad(learning_rate, x, y, theta = np.array([1, 1, 1, 1])):
    iterations = 0
    theta = theta
    mycost = cost(theta, x, y)
    while mycost > 0.05:
        theta = theta - (gradient(theta, x, y) * learning_rate)
        mycost = cost(theta, x, y)
        iterations += 1
    
    return theta, mycost, iterations

In [431]:
variables, workcost, iterations = LogisticRegression_grad(.001, X_train, y_train)
print(variables, workcost, iterations)

[ 4.25087503  7.55702624 -7.53709239 -7.08051829] 0.04999891847137795 13243


In [432]:
predict_train = np.array(list(map(round, sygmoid(variables, X_train))))
predict_test = np.array(list(map(round, sygmoid(variables, X_test))))
print(iris_error(predict_train, y_train))
print(iris_error(predict_test, y_test))

(0, 0.0)
(3, 0.1)


In [418]:
#Логистическая регрессия, обучающаяся методом nesterov momentum
def LogisticRegression_nesterov(gamma, lr, x, y, theta = np.array([1, 1, 1, 1])):
    iterations = 0
    theta = exp_mean = theta
    mycost = cost(theta, x, y)
    while mycost > 0.01:
        exp_mean = gamma * exp_mean + lr * gradient(theta - gamma * exp_mean, x, y)
        theta = theta - exp_mean
        mycost = cost(theta, x, y)
        iterations += 1
    
    return theta, mycost, iterations

In [419]:
#Варианты применения с разными значениями gamma
variables, workcost, iterations = LogisticRegression_nesterov(.9, .1, X_train, y_train)
print(variables, workcost, iterations)

<ipython-input-412-d60f6549ff0d>:4: RuntimeWarning: divide by zero encountered in log
  value = (- y) * np.log(sygm) - (1 - y) * np.log(1 - sygm)


[ 124.06252931  139.0203686  -192.12096266 -140.89504943] 0.00877524426570839 149


In [420]:
predict_train = np.array(list(map(round, sygmoid(variables, X_train))))
predict_test = np.array(list(map(round, sygmoid(variables, X_test))))
print(iris_error(predict_train, y_train))
print(iris_error(predict_test, y_test))

(0, 0.0)
(3, 0.1)


In [421]:
variables, workcost, iterations = LogisticRegression_nesterov(.25, .1, X_train, y_train)
print(variables, workcost, iterations)

<ipython-input-412-d60f6549ff0d>:4: RuntimeWarning: divide by zero encountered in log
  value = (- y) * np.log(sygm) - (1 - y) * np.log(1 - sygm)


[ 54.95024048  76.09972379 -90.8058987  -71.37373792] 0.009995847412906093 594


In [422]:
predict_train = np.array(list(map(round, sygmoid(variables, X_train))))
predict_test = np.array(list(map(round, sygmoid(variables, X_test))))
print(iris_error(predict_train, y_train))
print(iris_error(predict_test, y_test))

(0, 0.0)
(3, 0.1)


In [423]:
#Самый удачный вариант, и по точности, и по количеству итераций. 
#Видно, что nesterov momentum находит минимум на два порядка быстрее, чем обычный градиентный спуск
variables, workcost, iterations = LogisticRegression_nesterov(.975, .1, X_train, y_train)
print(variables, workcost, iterations)

[ 363.26190313  399.95574486 -555.2649747  -419.71449405] 0.0032575030951881843 115


<ipython-input-412-d60f6549ff0d>:4: RuntimeWarning: divide by zero encountered in log
  value = (- y) * np.log(sygm) - (1 - y) * np.log(1 - sygm)


In [424]:
predict_train = np.array(list(map(round, sygmoid(variables, X_train))))
predict_test = np.array(list(map(round, sygmoid(variables, X_test))))
print(iris_error(predict_train, y_train))
print(iris_error(predict_test, y_test))

(0, 0.0)
(2, 0.06666666666666667)


In [425]:
#Логистическая регрессия, обучающаяся методом rmsprop
def LogisticRegression_rmsprop(gamma, lr, x, y, eps = 0.000001, theta = np.array([1, 1, 1, 1])):
    iterations = 0
    theta = exp_mean = theta
    mycost = cost(theta, x, y)
    while mycost > 0.05:
        exp_mean = exp_mean * gamma + gradient(theta, x, y) ** 2 * (1 - gamma)
        theta = theta - lr / np.sqrt(exp_mean + eps) * gradient(theta, x, y)
        mycost = cost(theta, x, y)
        iterations += 1
    
    return theta, mycost, iterations

In [426]:
variables, workcost, iterations = LogisticRegression_rmsprop(.2, .01, X_train, y_train)
print(variables, workcost, iterations)

[ 3.62399945  8.26381161 -6.62324035 -8.64903223] 0.04999274091386929 3188


In [427]:
# На этой выборке вариант с rmsprop отрабатывает не очень хорошо, но все равно значительно быстрее, чем обычный градиентный спуск.
predict_train = np.array(list(map(round, sygmoid(variables, X_train))))
predict_test = np.array(list(map(round, sygmoid(variables, X_test))))
print(iris_error(predict_train, y_train))
print(iris_error(predict_test, y_test))

(1, 0.014285714285714285)
(3, 0.1)
